# Generated by Django 2.2.4 on 2021-08-03 21:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
                ('editors', django.db.models.manager.Manager()),
            ],
        ),
    ]
