# Generated by Django 2.2.4 on 2021-08-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20210803_1759'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
            ],
        ),
    ]
